version1/website/models.py
from website import db

class Devices(db.Model):

    __tablename__ = 'devices_table'
    id = db.Column(db.Integer,primary_key=True)
    hostname = db.Column(db.Text)
    ip = db.Column(db.Text)
    sw_version = db.Column(db.Text)
    model = db.Column(db.Text)
    os_type = db.Column(db.Text)
    chassis_sn = db.Column(db.Text)
    uptime = db.Column(db.Text)

    def __repr__(self):
        return f"You selected: : {self.hostname}, IP is: {self.ip}, OS family is : {self.os_type}"

version1/website/devices/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, IntegerField, SubmitField, RadioField, EmailField, StringField
from wtforms.validators import DataRequired


class DeviceForm(FlaskForm):
        ip = TextAreaField('IP Address of Device', validators=[DataRequired()])
        submit = SubmitField('Submit')

version1/website/devices/views.py
from flask import Blueprint, render_template, redirect, url_for, session
from website.db_controller import DBcontroller
from website.devices.forms import DeviceForm
from website.devices.background_processes import CiscoCommands
from website.models import Devices


devices_blueprint = Blueprint('devices',__name__,
                                    template_folder='templates/devices')

@devices_blueprint.route('/info', methods = ['GET', 'POST'])
def info():

    form = DeviceForm()
    if form.validate_on_submit():
        # Split string on comma and append to a list
        session['ip'] = form.ip.data
        ips = session.get('ip', None).replace(" ", "").replace("\r\n\r\n", "").replace("\r\n", "").lower().split(',')

        # Uncomment below once list of IPs created
        error_ips = []
        show_ver = CiscoCommands()
        # hostname,ip,sw_version,model,os_type,chassis_sn,uptime = show_ver.show_version(ip)
        genie_list, error_ips = show_ver.create_threads(ips)

        # Add to DB
        device_inventory = DBcontroller()
        for device in genie_list:
            device_inventory.update_device_inventory(
                                                device['Hostname'], 
                                                device['IP'], 
                                                device['Version'], 
                                                device['Model'], 
                                                device['OS'], 
                                                device['Chassis'], 
                                                device['Uptime'])
        device_inventory.close_db_conn()

        all_devices = Devices.query.all()
        return render_template('inventory.html', all_devices=all_devices, error_ips=error_ips)
    
    else:
        form = DeviceForm()
        return render_template('info.html', form=form)



@devices_blueprint.route('/inventory')
def inventory():

    all_devices = Devices.query.all()

    return render_template('inventory.html', all_devices=all_devices)

version1/website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Flask Scrapli Project</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/main.css') }}">
      </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="{{ url_for('index') }}">Inventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('devices.info') }}">Device Info</a>
                </li> 
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('devices.inventory') }}">Device Inventory</a>
                </li>  


                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">?Something?</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href=#>Check a Domain</a>
                    <a class="dropdown-item" href=#>List all Domains</a>
                    <a class="dropdown-item" href=#>Domain Database Upload</a>
                  </div>
                </li>

            </div>
          </nav>
        {% block content %}



        
        {% endblock %}
            <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">
            <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
            <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>
        {% block scripts %}
        


        


        {% endblock %}

        
    </body>
</html>